"""P5R-H SS8: the package status table, generated by reconciliation.

The six-state README table is no longer written by hand. Every item
carries a machine check; a declared status of "Closed--integrated" that
fails its check is DOWNGRADED automatically and the failure reason is
printed into the table. This is the mechanism behind the rule that
"Closed" may only be used where the five-layer facts gate (or an
equivalent executable check) can prove it.

Declarations: docs/ir_status_declarations.json
Emits:        internal_review/ir_staging/STATUS_TABLE.md  (+ .json audit)

    env PYTHONHASHSEED=2025 python reporting/status_table.py [--selftest]
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

CODE_ROOT = Path(__file__).resolve().parent.parent
import sys as _sys
_sys.path.insert(0, str(CODE_ROOT))
#: paper_R1 is main/ + esm/ since P7-A SS2; a package's assembled
#: view is still flat. One resolver answers for all three layouts.
from experiments.package_layout import paper_file  # noqa: E402

ROOT = CODE_ROOT.parent
PAPER = ROOT / "paper_R1"
OUTDIR = CODE_ROOT / "reporting" / "out"
STAGING = ROOT / "internal_review" / "ir_staging"
DECL = CODE_ROOT / "docs" / "ir_status_declarations.json"

STATES = ["Closed--integrated",
          # P5R-K SS7.2: rows whose closure is a visual or semantic
          # judgment cannot be settled by a lexical check. They may be
          # closed, but only against a named entry in the manual
          # page-inspection log, which the check below verifies exists.
          "Verified-by-inspection",
          "Analysis complete--not integrated",
          "Partially closed",
          "Evidence not supplied in review package",
          "In flight"]
#: the manual per-page acceptance log a Verified-by-inspection row binds to
INSPECTION_LOG = ROOT / "internal_review" / "ir_staging" / "INSPECTION_LOG.md"
#: a failed check can never leave an item above this
DOWNGRADE_TO = "Partially closed"


def _resolve(rel: str) -> Path:
    """A declared path, resolved wherever this table is being built.

    Declarations are written in REPOSITORY terms. In package mode the same
    content sits at different paths, and this resolver used to try exactly one
    candidate (ROOT / rel) -- so a package-mode rebuild reported four rows
    missing evidence the package actually carried, at a different shape. Same
    two mappings package_gates uses, exact in both cases, neither a basename
    fallback: the rest of the path still has to match.
    """
    rel = rel.lstrip("./")
    cands = [ROOT / rel, CODE_ROOT / rel, STAGING / rel]
    if rel.startswith("code_SNI/"):
        cands.append(STAGING / "code" / rel[len("code_SNI/"):])
    if rel.startswith("internal_review/ir_staging/"):
        cands.append(STAGING / rel[len("internal_review/ir_staging/"):])
    if rel.startswith("paper_R1/"):
        #: ORDER MATTERS, and it did not used to. In a PACKAGE the sources
        #: under source/ are the truth -- the package is the delivered unit
        #: and there is nothing else. In a WORKING TREE they are not:
        #: internal_review/ir_staging/source/ is an unmanaged leftover that
        #: no build reads and nothing refreshes, and preferring it meant the
        #: status table spent this round auditing a pre-backfill copy of the
        #: manuscript. It reported two \pending placeholders that the live
        #: file no longer had. Gate 5 caught it only because the package-mode
        #: rebuild disagreed with the working-tree one.
        live = paper_file(rel[len("paper_R1/"):], PAPER)
        staged = STAGING / "source" / rel[len("paper_R1/"):]
        in_pkg = (STAGING / "BUILD.json").exists()
        cands += ([staged, live] if in_pkg else [live, staged])
    for c in cands:
        if c.exists():
            return c
    return ROOT / rel          # the path as declared, for the error message


def _norm(t: str) -> str:
    return re.sub(r"\s+", " ", t)


def _layers() -> dict:
    """The text layers a check may address."""
    tex = " ".join(_norm(re.sub(r"(?<!\\)%.*", "",
                                paper_file(f, PAPER).read_text()))
                   for f in ("paperY_main.tex", "paperY_ESM.tex"))
    out = " ".join(_norm(p.read_text()) for p in sorted(OUTDIR.glob("*.tex")))
    pdf = ""
    for f in ("paperY_main.pdf", "paperY_ESM.pdf"):
        p = paper_file(f, PAPER)
        if p.exists():
            pdf += " " + _norm(subprocess.run(
                ["pdftotext", str(p), "-"], capture_output=True,
                text=True).stdout)
    #: pdftotext breaks a long URL across lines, so `github.com/oudeng/VERA`
    #: is really "github.com/oudeng/VE RA" in the extracted text -- and a
    #: withdrawn string could hide behind the same break from an ABSENCE
    #: check, which is the dangerous direction. This layer removes every
    #: space so a pattern matches the document rather than the line breaking.
    pdf_nows = re.sub(r"\s+", "", pdf)
    return {"tex": tex, "out": out, "pdf": pdf, "pdf_nows": pdf_nows,
            "all": tex + " " + out + " " + pdf}


def _dig(obj, path: str):
    cur = obj
    for part in path.split("."):
        if isinstance(cur, list):
            cur = cur[int(part)]
        else:
            cur = cur[part]
    return cur


def _uncheckable(audit: list) -> str:
    """Which rows carry no executable check, named from the rows themselves.

    This sentence used to name `2.20 and 8.5` as literals. 2.20 was closed
    with a real check on 2026-09-05 and the sentence went on saying it had
    none -- a stale claim inside the document whose whole job is to have no
    stale claims.
    """
    ids = [a["id"] for a in audit if a["check"] == "none"]
    if not ids:
        return "no row declares itself without one"
    return (f"{' and '.join(ids)} declare"
            f"{'s' if len(ids) == 1 else ''} itself with no executable check, "
            f"which is why {'it is' if len(ids) == 1 else 'they are'} not closed")


def run_check(chk: dict, layers: dict) -> tuple:
    """(passed, detail). Every branch either proves something or fails."""
    kind = chk["type"]
    if kind == "facts_gate":
        sys.path.insert(0, str(CODE_ROOT))
        from reporting import facts_gate
        r = facts_gate.run(include_pdf=chk.get("include_pdf", True))
        return (r["pass"],
                f"facts_gate: {r['n_variant_hits']} variant hits, "
                f"{r['n_numeric_errors']} numeric errors, "
                f"{r.get('n_generators_scanned', 0)} generators scanned")
    if kind == "absent":
        where = chk.get("layer", "all")
        hits = [p for p in chk["patterns"]
                if re.search(p, layers[where], re.I)]
        return (not hits, f"absent in {where}" if not hits
                else f"still present in {where}: {hits}")
    if kind == "present":
        where = chk.get("layer", "all")
        miss = [p for p in chk["patterns"]
                if not re.search(p, layers[where], re.I)]
        return (not miss, f"present in {where}" if not miss
                else f"missing from {where}: {miss}")
    if kind == "json_field":
        p = _resolve(chk["file"])
        if not p.exists():
            return (False, f"artifact missing: {chk['file']}")
        try:
            v = _dig(json.loads(p.read_text()), chk["path"])
        except (KeyError, IndexError, ValueError) as e:
            return (False, f"{chk['file']}#{chk['path']}: {e}")
        if "equals" in chk:
            return (v == chk["equals"],
                    f"{chk['path']} = {v!r} (want {chk['equals']!r})")
        return (True, f"{chk['path']} = {v!r}")
    if kind == "file_exists":
        missing = [f for f in chk["files"] if not _resolve(f).exists()]
        return (not missing, "all present" if not missing
                else f"missing: {missing}")
    if kind == "attested":
        p = _resolve(chk["file"])
        if not p.exists():
            return (False, f"receipt missing: {chk['file']}")
        t = _norm(p.read_text())
        miss = [a for a in chk["anchors"] if a not in t]
        return (not miss, f"attested in {chk['file']}" if not miss
                else f"anchor absent from {chk['file']}: {miss}")
    if kind == "fresher_than":
        # An artifact that must be newer than the source it is built from.
        # Build-order staleness is invisible to text checks (a figure can
        # print a superseded number that the prose has already corrected).
        a = _resolve(chk["artifact"])
        srcs = [_resolve(f) for f in chk["sources"]]
        if not a.exists():
            return (False, f"artifact missing: {chk['artifact']}")
        missing = [str(x) for x in srcs if not x.exists()]
        if missing:
            return (False, f"source missing: {missing}")
        def _mtime(path: Path) -> float:
            """mtime, from BUILD.json when we are inside a package.

            Unzipping discards mtimes, so every file in an extracted package
            shares a timestamp and a freshness question becomes unanswerable
            -- it answered "stale" at random. The build records the real ones
            for exactly the files these checks name; gate 12 already reads
            them, and this is the same fact read by the same rule.
            """
            bj = STAGING / "BUILD.json"
            if bj.exists():
                try:
                    sm = json.loads(bj.read_text()).get("source_mtimes", {})
                except Exception:
                    sm = {}
                for rel, t in sm.items():
                    if str(path).endswith(rel):
                        return float(t)
            return path.stat().st_mtime

        stale = [x.name for x in srcs if _mtime(x) > _mtime(a)]
        return (not stale,
                f"{Path(chk['artifact']).name} is newer than its sources"
                if not stale else
                f"{Path(chk['artifact']).name} predates {stale}")
    if kind == "count_at_least":
        p = _resolve(chk["file"])
        if not p.exists():
            return (False, f"file missing: {chk['file']}")
        n = len(re.findall(chk["pattern"], p.read_text()))
        return (n >= chk["minimum"],
                f"{n} matches of {chk['pattern']!r} (need "
                f">= {chk['minimum']})")
    if kind == "all_of":
        details = []
        okall = True
        for sub in chk["checks"]:
            o, d = run_check(sub, layers)
            okall = okall and o
            details.append(("ok" if o else "FAIL") + ": " + d)
        return (okall, " | ".join(details))
    if kind == "inspection":
        # P5R-K SS7.2. A visual/semantic row closes only against a named
        # entry in the manual page-inspection log; no log entry, no closure.
        if not INSPECTION_LOG.exists():
            return (False, "INSPECTION_LOG.md not present in the package")
        log = _norm(INSPECTION_LOG.read_text())
        miss = [a for a in chk["anchors"] if a not in log]
        if miss:
            return (False, f"no inspection-log entry for: {miss}")
        verdict = chk.get("require_verdict", "PASS")

        def _recorded(anchor: str) -> bool:
            # An anchor may appear more than once (the log's defect summary
            # names pages too); the row that carries the verdict is what
            # counts, so every occurrence is considered.
            i = log.find(anchor)
            while i != -1:
                if verdict in log[i: i + 400]:
                    return True
                i = log.find(anchor, i + 1)
            return False

        bad = [a for a in chk["anchors"] if not _recorded(a)]
        return (not bad,
                f"inspection log records {verdict} for {chk['anchors']}"
                if not bad else
                f"inspection log does not record {verdict} for: {bad}")
    if kind == "none":
        # No executable check exists -> cannot be Closed. Stated, not hidden.
        return (False, "no executable check defined for this item")
    raise ValueError(f"unknown check type {kind!r}")


def build(decl_path: Path = DECL, out_md: Path = None,
          out_json: Path = None) -> dict:
    decl = json.loads(decl_path.read_text())
    layers = _layers()
    rows, audit = [], []
    for item in decl["items"]:
        assert item["declared"] in STATES, item["declared"]
        ok, detail = run_check(item["check"], layers)
        final = item["declared"]
        note = ""
        if not ok and STATES.index(final) < STATES.index(DOWNGRADE_TO):
            final = DOWNGRADE_TO
            note = f" **[auto-downgraded: {detail}]**"
        rows.append({"id": item["id"], "title": item["title"],
                     "status": final, "evidence": item["evidence"] + note})
        audit.append({"id": item["id"], "declared": item["declared"],
                      "final": final, "check": item["check"]["type"],
                      "passed": ok, "detail": detail})
    n_down = sum(1 for a in audit if a["declared"] != a["final"])
    md = ["# IR package status table (generated -- do not edit by hand)",
          "",
          f"Generated by `code/reporting/status_table.py` from "
          f"`gate_inputs/code_SNI/docs/ir_status_declarations.json`. "
          f"Every **Closed** or **Verified** row carries an executable "
          f"check, and a declared *Closed--integrated* that fails its check "
          f"is downgraded automatically. A row that is not closed may carry "
          f"a non-closing check or none at all: {_uncheckable(audit)}. "
          f"Items downgraded this run: **{n_down}**.",
          "",
          "Vocabulary: " + " / ".join(f"**{s}**" for s in STATES) + ".",
          "",
          "| # | Item (third review SS2 / this round) | Status | Evidence |",
          "|---|---|---|---|"]
    for r in rows:
        md.append(f"| {r['id']} | {r['title']} | {r['status']} | "
                  f"{r['evidence']} |")
    md.append("")
    md.append(f"Rows: {len(rows)}. Closed--integrated: "
              f"{sum(1 for r in rows if r['status'] == STATES[0])}. "
              f"Auto-downgraded: {n_down}.")
    text = "\n".join(md) + "\n"
    if out_md is None:
        out_md = STAGING / "STATUS_TABLE.md"
    if out_json is None:
        out_json = STAGING / "STATUS_TABLE.audit.json"
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text(text)
    out_json.write_text(json.dumps(
        {"n_items": len(rows), "n_downgraded": n_down, "audit": audit},
        indent=1))
    return {"n_items": len(rows), "n_downgraded": n_down,
            "downgraded": [a for a in audit if a["declared"] != a["final"]],
            "md": out_md, "json": out_json}


def _bootstrap_if_in_package() -> str:
    """Rebind the roots when this script is run standalone inside a package.

    The gate process rebinds these globals before calling in; a SUBPROCESS
    gets none of that, and a subprocess is how gate 17 runs this and how a
    reader runs it. Rather than invent a second mapping from package shape to
    repository shape, use the one that already exists -- package_layout is the
    single place that knows it.
    """
    global ROOT, CODE_ROOT, PAPER, OUTDIR, STAGING, DECL, INSPECTION_LOG
    here = Path(__file__).resolve().parent.parent          # <pkg>/code
    pkg = here.parent
    if PAPER.exists() or not (pkg / "gate_inputs").is_dir():
        return ""
    sys.path.insert(0, str(here / "experiments"))
    from package_layout import roots, materialise_paper
    view = materialise_paper(pkg)
    r = roots(pkg, view)
    ROOT, CODE_ROOT = r["ROOT"], r["CODE_ROOT"]
    PAPER, OUTDIR, STAGING = r["PAPER"], r["OUTDIR"], r["STAGING"]
    DECL = CODE_ROOT / "docs" / "ir_status_declarations.json"
    INSPECTION_LOG = STAGING / "INSPECTION_LOG.md"
    return f"(package mode: roots rebound from {pkg})"


def _declarations() -> Path:
    """The declarations file, found from wherever this script was started.

    Inside the gate process the module globals are rebound to the package.
    A SUBPROCESS gets none of that -- and gate 17 runs this script as a
    subprocess, which is also exactly how a reader runs it. So the standalone
    command has to find the file by itself, or the top tier of "this script
    runs in the package" is a claim about a command that does not work.
    """
    here = Path(__file__).resolve().parent.parent          # <pkg>/code or code_SNI
    for c in (DECL,
              here / "docs" / "ir_status_declarations.json",
              here.parent / "gate_inputs" / "code_SNI" / "docs"
              / "ir_status_declarations.json"):
        if c.exists():
            return c
    return DECL


def check(md_delivered: Path, json_delivered: Path = None) -> dict:
    """Re-render here and compare, character by character, with what shipped.

    P5R-Y. Gate 5 already rebuilt the table inside the package -- but it
    compared only the MARKDOWN. The audit JSON was rebuilt into the same
    temporary directory and then never read, and the audit JSON is the half
    that carries `passed: true` per row. The document a human reads was being
    checked; the record a machine reads was not -- and it is the machine's
    record that the whole artifact exists to make checkable.

    Both are compared by identical BYTES rather than by parsed equality: a
    JSON that parses the same but renders differently is still a delivered
    file nobody can reproduce.
    """
    import tempfile
    out = {"md": str(md_delivered), "json": str(json_delivered or "")}
    with tempfile.TemporaryDirectory(prefix="status_check_") as td:
        d = Path(td)
        r = build(_declarations(), d / "t.md", d / "t.json")
        want_md = md_delivered.read_text() if md_delivered.exists() else None
        got_md = (d / "t.md").read_text()
        out["md_ok"] = want_md == got_md
        out["md_chars"] = len(got_md)
        if json_delivered is not None:
            want_j = (json_delivered.read_text()
                      if json_delivered.exists() else None)
            got_j = (d / "t.json").read_text()
            out["json_ok"] = want_j == got_j
            out["json_chars"] = len(got_j)
        else:
            out["json_ok"] = True
            out["json_chars"] = 0
        out["n_items"] = r["n_items"]
        out["n_downgraded"] = r["n_downgraded"]
    out["pass"] = bool(out["md_ok"] and out["json_ok"])
    parts = ["STATUS_TABLE.md: " + ("character-identical" if out["md_ok"]
                                    else "DIFFERS")
             + f" ({out['md_chars']} chars)"]
    if json_delivered is not None:
        parts.append("STATUS_TABLE.audit.json: "
                     + ("character-identical" if out["json_ok"] else "DIFFERS")
                     + f" ({out['json_chars']} chars)")
    out["detail"] = ("; ".join(parts) + f"; {out['n_items']} rows, "
                     f"{out['n_downgraded']} auto-downgraded on this rebuild")
    return out


def _selftest() -> int:
    import tempfile
    ok = True

    def check(c, m):
        nonlocal ok
        print(("[PASS] " if c else "[FAIL] ") + m)
        ok = ok and bool(c)

    with tempfile.TemporaryDirectory() as td:
        d = Path(td)
        decl = {"items": [
            {"id": "A", "title": "passes", "declared": "Closed--integrated",
             "evidence": "e", "check": {"type": "file_exists",
                                        "files": ["code_SNI/reporting/status_table.py"]}},
            {"id": "B", "title": "fails", "declared": "Closed--integrated",
             "evidence": "e", "check": {"type": "file_exists",
                                        "files": ["nope/does_not_exist"]}},
            {"id": "C", "title": "no check", "declared": "Closed--integrated",
             "evidence": "e", "check": {"type": "none"}},
            {"id": "D", "title": "honest in flight", "declared": "In flight",
             "evidence": "e", "check": {"type": "none"}},
        ]}
        dp = d / "decl.json"
        dp.write_text(json.dumps(decl))
        r = build(dp, d / "t.md", d / "t.json")
        t = (d / "t.md").read_text()
        check(r["n_downgraded"] == 2, "two failing Closed rows downgraded")
        check("| A | passes | Closed--integrated" in t, "passing row keeps Closed")
        check("auto-downgraded" in t, "downgrade reason printed in the table")
        check("| D | honest in flight | In flight" in t,
              "an honestly-declared In flight row is never downgraded")
        ids = [a["id"] for a in json.loads((d / "t.json").read_text())["audit"]]
        check(ids == ["A", "B", "C", "D"], "audit covers every row in order")

    # --check on the real pair, and on a tampered one. The JSON half is the
    # point: it is what carries `passed: true` per row, and it was the half
    # nothing compared (P5R-Y).
    import shutil as _sh
    real_md = STAGING / "STATUS_TABLE.md"
    real_js = STAGING / "STATUS_TABLE.audit.json"
    if real_md.exists() and real_js.exists():
        r = globals()["check"](real_md, real_js)
        check(r["pass"] and r["md_ok"] and r["json_ok"],
              "--check: the delivered pair reproduces character for character")
        with tempfile.TemporaryDirectory() as td2:
            d2 = Path(td2)
            _sh.copy2(real_md, d2 / "STATUS_TABLE.md")
            _sh.copy2(real_js, d2 / "STATUS_TABLE.audit.json")
            # markdown untouched, ONE character changed in the audit JSON
            j = (d2 / "STATUS_TABLE.audit.json").read_text()
            (d2 / "STATUS_TABLE.audit.json").write_text(
                j.replace('"passed": false', '"passed": true', 1)
                if '"passed": false' in j else j[:-1])
            r2 = globals()["check"](d2 / "STATUS_TABLE.md",
                                    d2 / "STATUS_TABLE.audit.json")
            check(r2["md_ok"] and not r2["json_ok"] and not r2["pass"],
                  "--check: an edited audit JSON is RED even when the "
                  "markdown still matches")
    return 0 if ok else 1


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--check", metavar="STATUS_TABLE.md",
                    help="re-render the table here and compare it, and its "
                         "audit JSON, character by character with the "
                         "delivered pair")
    a = ap.parse_args()
    if a.selftest:
        raise SystemExit(_selftest())
    if a.check:
        note = _bootstrap_if_in_package()
        if note:
            print(f"[mode] {note}")
        md = Path(a.check)
        if not md.exists():
            # inside a package the delivered pair sits at the package root,
            # while this script runs from <pkg>/code -- the same resolution
            # change_summary.py uses for the same reason
            here = Path(__file__).resolve().parent.parent
            md = here.parent / Path(a.check).name
        if not md.exists():
            print(f"[FAIL] cannot find {a.check}")
            raise SystemExit(1)
        aud = md.with_name(md.stem + ".audit.json")
        r = check(md, aud if aud.exists() else None)
        print(("[OK] " if r["pass"] else "[RED] ") + r["detail"])
        raise SystemExit(0 if r["pass"] else 1)
    r = build()
    print(json.dumps({"n_items": r["n_items"], "n_downgraded": r["n_downgraded"]}))
    for d in r["downgraded"]:
        print(f"[DOWNGRADED] {d['id']}: {d['detail']}")
    print(f"[ok] wrote {r['md']}")
    raise SystemExit(0)
