"""T2.2(c)+(d): assemble the mask diagnostics and the real-vs-simulated study
into the artifacts the checkpoint report and the supplement need.

Produces, under `results/T2.2_masks/`:

    diag_summary.csv         six-item table, one row per (dataset, mechanism, rate)
    diag_sensitivity.csv     per-column response to each driver (item 4)
    diag_rate_stability.csv  log-odds contrast across rates (item 5)
    diag_legacy_summary.csv  the same six items for R0's mechanism, for contrast
    real_vs_simulated.json   the four-axis CDC comparison
    fig_real_vs_simulated.{png,pdf}
    T2.2_diagnostics.md      the readable version

The legacy set is regenerated rather than quoted so that the comparison is
between two mask sets made by one generator under one seed policy, which is the
only way the difference can be attributed to the mechanism rather than to the
implementation.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict

import pandas as pd
import yaml

from . import diagnostics as D
from . import real_vs_simulated as RS

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "results" / "T2.2_masks"
MASKS = ROOT / "data" / "masks"


def _tables() -> Dict[str, Path]:
    cfg = yaml.safe_load((ROOT / "configs" / "datasets.yaml").read_text())
    out = {}
    for name, blk in cfg["datasets"].items():
        p = Path(blk["complete_path"])
        out[name] = p if p.is_absolute() else ROOT / p
    return out


def _md_table(df: pd.DataFrame, cols=None, floatfmt="{:.4f}") -> str:
    d = df[cols] if cols else df
    head = "| " + " | ".join(str(c) for c in d.columns) + " |"
    rule = "|" + "|".join("---" for _ in d.columns) + "|"
    lines = [head, rule]
    for _, r in d.iterrows():
        cells = []
        for v in r:
            if isinstance(v, float):
                cells.append(floatfmt.format(v))
            elif isinstance(v, bool):
                cells.append("yes" if v else "**no**")
            else:
                cells.append(str(v))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(OUT))
    ap.add_argument("--skip-cdc", action="store_true")
    a = ap.parse_args()
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)

    tables = _tables()

    # ---- items 1-6 on the published masks -------------------------------
    new = D.diagnose_grid(MASKS / "clinical_v1", tables)
    new["summary"].to_csv(out / "diag_summary.csv", index=False)
    new["sensitivity"].to_csv(out / "diag_sensitivity.csv", index=False)
    new["rate_stability"].to_csv(out / "diag_rate_stability.csv", index=False)

    # ---- the same six items on R0's mechanism ---------------------------
    legacy = D.diagnose_grid(MASKS / "legacy_R0", tables)
    legacy["summary"].to_csv(out / "diag_legacy_summary.csv", index=False)

    s, ls = new["summary"], legacy["summary"]
    md = ["# T2.2 mask diagnostics", "",
          f"{len(s)} generated masks under `clinical_v1`, "
          f"{len(ls)} under `record_index_ID` (R0's mechanism, regenerated by "
          f"the same code so the comparison isolates the mechanism).", ""]

    # item 1
    md += ["## Item 1 - does the mask still encode row order?", "",
           f"Threshold |r| < {D.ROW_INDEX_THRESHOLD}. Calibration: the real "
           f"CDC2022 missingness pattern sits at -0.0186 over 445,132 rows, so "
           f"the threshold admits a genuine pattern comfortably.", ""]
    if not s.empty:
        fail = s[~s.row_index_pass]
        md += [f"Passing: **{int(s.row_index_pass.sum())}/{len(s)}**.", ""]
        if len(fail):
            md += ["Not passing, listed individually (item 2 attributes each):", "",
                   _md_table(fail, ["dataset", "mechanism", "rate", "row_index_r",
                                    "row_index_sigmas"]), ""]
        if not ls.empty:
            md += [f"R0's mechanism, same tables: "
                   f"**{int(ls.row_index_pass.sum())}/{len(ls)}** passing, "
                   f"worst |r| = {ls.row_index_r.abs().max():.4f}.", ""]

    # item 3
    md += ["## Item 3 - did every column hit its target rate?", "",
           f"Tolerance {D.RATE_TOLERANCE}. R0 could overshoot badly: its MNAR "
           f"categorical split sent one column to 37.8% against a 30% target "
           f"(B39).", ""]
    if not s.empty:
        md += [f"Worst |achieved - target| over all masks and columns: "
               f"**{s.max_abs_rate_error.max():.5f}**; masks with any column out "
               f"of tolerance: **{int((s.n_columns_out_of_tolerance > 0).sum())}"
               f"/{len(s)}**.", ""]

    # item 5
    st = new["rate_stability"]
    md += ["## Item 5 - is the mechanism the same at 10 / 30 / 50 %?", "",
           "A logistic mechanism with a fixed coefficient keeps the top-decile "
           "versus bottom-decile log-odds contrast constant when only the target "
           "rate changes. R0's mean-linear rescale did not (2.19 / 2.70 / 4.06, "
           "a 63 % spread) -- finding B49. The synthetic sampling floor for this "
           "statistic is about 7.5 %.", ""]
    if not st.empty:
        worst = st.sort_values("rel_spread", ascending=False).head(8)
        md += [_md_table(worst, ["dataset", "mechanism", "driver", "mean",
                                 "spread", "rel_spread"]), ""]

    # item 6
    md += ["## Item 6 - are the MAR drivers observable?", ""]
    if not s.empty:
        bad = s[~s.drivers_fully_observed]
        md += [f"Masks in which every declared driver is fully observed: "
               f"**{int(s.drivers_fully_observed.sum())}/{len(s)}**.", ""]
        if len(bad):
            md += ["**Violations** -- a masked driver makes the mechanism MNAR "
                   "while the config still calls it MAR:", "",
                   _md_table(bad, ["dataset", "mechanism", "rate",
                                   "driver_missing_counts"]), ""]

    # ---- CDC real vs simulated ------------------------------------------
    if not a.skip_cdc:
        sims = {}
        for mech in ("MCAR", "MAR", "MNAR"):
            try:
                b = D.load_bundle(MASKS / "clinical_v1", "CDC2022", mech, 0.3,
                                  tables["CDC2022"])
            except (FileNotFoundError, KeyError):
                continue
            sims[f"simulated {mech}@30%"] = b.mask
        if sims:
            ao = (yaml.safe_load((ROOT / "configs" / "datasets.yaml").read_text())
                  ["datasets"]["CDC2022"].get("always_observed", []) or [])
            cmp = RS.compare(sims, always_observed=list(ao) + ["ID"])
            (out / "real_vs_simulated.json").write_text(cmp.to_json())
            cmp.per_column.to_csv(out / "real_vs_simulated_per_column.csv",
                                  index=False)
            RS.make_figure(cmp, out / "fig_real_vs_simulated.png",
                           out / "fig_real_vs_simulated.pdf")
            md += ["## Real versus simulated missingness (CDC2022)", "",
                   "The specification for CDC2022 was written from "
                   "survey-methodology principles and deliberately not fitted to "
                   "`heart_2022_with_nans.csv`, so this is a test rather than a "
                   "restatement of its own fit.", ""]
            md += ["- " + t for t in cmp.summary["interpretation"]] + [""]
            prop = cmp.summary.get("derived_variable_propagation") or {}
            if prop:
                md += [f"Derived-variable propagation: "
                       f"P(BMI missing | height or weight missing) = "
                       f"{prop['p_bmi_missing_given_height_or_weight_missing']:.4f}. "
                       f"An independent per-column simulation cannot reproduce "
                       f"this, and the supplement says so rather than leaving a "
                       f"reader to assume otherwise.", ""]
            md += ["![real versus simulated](fig_real_vs_simulated.png)", ""]
        else:
            md += ["## Real versus simulated missingness (CDC2022)", "",
                   "**Not produced**: no CDC2022 masks were found under "
                   f"`{MASKS / 'clinical_v1'}`.", ""]

    (out / "T2.2_diagnostics.md").write_text("\n".join(md))
    print("\n".join(md[:40]))
    print(f"\nwrote {out}/T2.2_diagnostics.md and 6 data files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
